baseURL: https://migact.net/
defaultContentLanguage: en
enableGitInfo: true
enableRobotsTXT: true
timeZone: Europe/Prague
disableKinds:
  - taxonomy
  - term
params:
  contact:
    phone: +420 774 324 035
    email: contact@migact.net
    ico: '19843631'
    databox: fdxji3v
    address:
      office: Revoluční 762/13, Praha 1, 110 00
      registration: Světova 523/1, Praha 8
  socials:
    facebook: https://www.facebook.com/migactinitiative
    instagram: https://www.instagram.com/mig.act/
    linkedin: https://www.linkedin.com/company/migact-initiative/
languages:
  en:
    languageName: English
    languageCode: en-US
    title: MigAct - Support of Civic Engagement
    weight: 1
    params:
      description: Supporting civic engagement and community building for people with
        migration backgrounds in Prague
  cs:
    languageName: Čeština
    languageCode: cs-CZ
    title: MigAct - Podpora občanské angažovanosti
    weight: 2
    params:
      description: Podpora občanské angažovanosti a budování komunity pro lidi s migračním
        pozadím v Praze
    permalinks:
      page:
        projects: /projekty/:slug/
      section:
        projects: /projekty/
minify:
  minifyOutput: true
outputFormats:
  calendar:
    baseName: invitation
markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true