baseURL: https://migact.net/
defaultContentLanguage: en
enableGitInfo: true
enableRobotsTXT: true
timeZone: Europe/Prague
disableKinds:
  - taxonomy
  - term
params:
  contact:
    phone: +420 774 324 035
    email: contact@migact.net
    ico: '19843631'
    databox: fdxji3v
    address:
      office: Revoluční 762/13, Praha 1, 110 00
      registration: Světova 523/1, Praha 8
  newsletter: https://2989c05a.sibforms.com/serve/MUIFALW0J6CnxbjAGy7C2dsOFYgIFoOzRy0yACp00IUtr70Zkc5QcABcb87f-bxzTIoxdqxt4-Mxjw30LvYM2g_miXoJJT8cilNA-eSpjz_8HMMEV2ewEaX53I_N6hsAwkrymSEXNrVOdls-n65l5_-0T7NNebwBF1aLKfwyNPvP497Ob1rtAzKJHpkgah4BaxxIIwKe-1GmeQ0a
  donate: https://www.darujme.cz/projekt/1210263
  donate_widget: https://www.darujme.cz/widget?token=ed4icktstrv1p84h
  socials:
    facebook: https://www.facebook.com/migactinitiative
    instagram: https://www.instagram.com/mig.act/
    linkedin: https://www.linkedin.com/company/migact-initiative/
languages:
  en:
    languageName: English
    languageCode: en-US
    title: MigAct - Support of Civic Engagement
    weight: 1
    params:
      description: Supporting civic engagement and community building for people with
        migration backgrounds in Prague
  cs:
    languageName: Čeština
    languageCode: cs-CZ
    title: MigAct - Podpora občanské angažovanosti
    weight: 2
    params:
      description: Podpora občanské angažovanosti a budování komunity pro lidi s migračním
        pozadím v Praze
    permalinks:
      page:
        events: /akce/:slug/
        projects: /projekty/:slug/
      section:
        events: /akce/
        partners: /partneri/
        projects: /projekty/
        team: /tym/
outputFormats:
  calendar:
    baseName: invitation
pagination:
  pagerSize: 18
minify:
  minifyOutput: true
markup:
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true