main:
  - identifier: about
    pageRef: /about
    weight: 10
  - identifier: team
    pageRef: /team
    weight: 20
  - identifier: events_news
    pageRef: /events-news
    weight: 30
  - identifier: projects
    pageRef: /projects
    weight: 40
  - identifier: join_us
    pageRef: /join-us
    weight: 50
  - identifier: contact
    pageRef: /contact
    weight: 60
footer:
  - identifier: newsletter
    pre: images/parchment.svg
    url: https://2989c05a.sibforms.com/serve/MUIFALW0J6CnxbjAGy7C2dsOFYgIFoOzRy0yACp00IUtr70Zkc5QcABcb87f-bxzTIoxdqxt4-Mxjw30LvYM2g_miXoJJT8cilNA-eSpjz_8HMMEV2ewEaX53I_N6hsAwkrymSEXNrVOdls-n65l5_-0T7NNebwBF1aLKfwyNPvP497Ob1rtAzKJHpkgah4BaxxIIwKe-1GmeQ0a
    weight: 10
  - identifier: donate
    pre: images/heart.svg
    url: https://www.darujme.cz/projekt/1210263
    weight: 20
  - identifier: projects
    pre: images/briefcase.svg
    pageRef: /projects
    weight: 30
  - identifier: events_news
    pre: images/calendar.svg
    pageRef: /events-news
    weight: 40